// Code generated by protoc-gen-go.
// source: dmx.proto
// DO NOT EDIT!

/*
Package transport is a generated protocol buffer package.

It is generated from these files:
	dmx.proto

It has these top-level messages:
	DMXCommand
	MIDICommand
	BarChange
	Command
*/
package transport

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DMXCommand struct {
	Universe uint32 `protobuf:"varint,1,opt,name=universe" json:"universe,omitempty"`
	Channel  uint32 `protobuf:"varint,2,opt,name=channel" json:"channel,omitempty"`
	Value    uint32 `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
}

func (m *DMXCommand) Reset()                    { *m = DMXCommand{} }
func (m *DMXCommand) String() string            { return proto.CompactTextString(m) }
func (*DMXCommand) ProtoMessage()               {}
func (*DMXCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DMXCommand) GetUniverse() uint32 {
	if m != nil {
		return m.Universe
	}
	return 0
}

func (m *DMXCommand) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *DMXCommand) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type MIDICommand struct {
	Channel uint32 `protobuf:"varint,1,opt,name=channel" json:"channel,omitempty"`
	Value   uint32 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
}

func (m *MIDICommand) Reset()                    { *m = MIDICommand{} }
func (m *MIDICommand) String() string            { return proto.CompactTextString(m) }
func (*MIDICommand) ProtoMessage()               {}
func (*MIDICommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MIDICommand) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *MIDICommand) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type BarChange struct {
	At        uint64 `protobuf:"varint,1,opt,name=at" json:"at,omitempty"`
	NoteValue uint32 `protobuf:"varint,2,opt,name=noteValue" json:"noteValue,omitempty"`
	NoteCount uint32 `protobuf:"varint,3,opt,name=noteCount" json:"noteCount,omitempty"`
	Speed     uint32 `protobuf:"varint,4,opt,name=speed" json:"speed,omitempty"`
}

func (m *BarChange) Reset()                    { *m = BarChange{} }
func (m *BarChange) String() string            { return proto.CompactTextString(m) }
func (*BarChange) ProtoMessage()               {}
func (*BarChange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *BarChange) GetAt() uint64 {
	if m != nil {
		return m.At
	}
	return 0
}

func (m *BarChange) GetNoteValue() uint32 {
	if m != nil {
		return m.NoteValue
	}
	return 0
}

func (m *BarChange) GetNoteCount() uint32 {
	if m != nil {
		return m.NoteCount
	}
	return 0
}

func (m *BarChange) GetSpeed() uint32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

type Command struct {
	DmxCommands  []*DMXCommand  `protobuf:"bytes,1,rep,name=dmxCommands" json:"dmxCommands,omitempty"`
	MidiCommands []*MIDICommand `protobuf:"bytes,2,rep,name=midiCommands" json:"midiCommands,omitempty"`
	BarChange    *BarChange     `protobuf:"bytes,3,opt,name=barChange" json:"barChange,omitempty"`
	Frame        uint64         `protobuf:"varint,4,opt,name=frame" json:"frame,omitempty"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Command) GetDmxCommands() []*DMXCommand {
	if m != nil {
		return m.DmxCommands
	}
	return nil
}

func (m *Command) GetMidiCommands() []*MIDICommand {
	if m != nil {
		return m.MidiCommands
	}
	return nil
}

func (m *Command) GetBarChange() *BarChange {
	if m != nil {
		return m.BarChange
	}
	return nil
}

func (m *Command) GetFrame() uint64 {
	if m != nil {
		return m.Frame
	}
	return 0
}

func init() {
	proto.RegisterType((*DMXCommand)(nil), "transport.DMXCommand")
	proto.RegisterType((*MIDICommand)(nil), "transport.MIDICommand")
	proto.RegisterType((*BarChange)(nil), "transport.BarChange")
	proto.RegisterType((*Command)(nil), "transport.Command")
}

func init() { proto.RegisterFile("dmx.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x37, 0x50, 0x7c, 0x01, 0x06, 0xab, 0x20, 0x0b, 0x31, 0x54, 0x99, 0x3a, 0x65,
	0x08, 0x03, 0x12, 0x12, 0x0b, 0xe9, 0xd2, 0xa1, 0x8b, 0x07, 0xd4, 0xd5, 0xc5, 0x86, 0x46, 0xaa,
	0xed, 0xc8, 0x71, 0xaa, 0xfe, 0x44, 0x7e, 0x16, 0xaa, 0x53, 0x27, 0x66, 0xe8, 0xf8, 0xee, 0xee,
	0xf3, 0xdd, 0x7b, 0x06, 0x2c, 0xd4, 0xb1, 0x68, 0xac, 0x71, 0x86, 0x60, 0x67, 0xb9, 0x6e, 0x1b,
	0x63, 0x5d, 0xbe, 0x01, 0x58, 0xae, 0x37, 0x95, 0x51, 0x8a, 0x6b, 0x41, 0x9e, 0xe0, 0xa6, 0xd3,
	0xf5, 0x41, 0xda, 0x56, 0xd2, 0x64, 0x9e, 0x2c, 0xee, 0xd8, 0xa0, 0x09, 0x85, 0xe9, 0xd7, 0x8e,
	0x6b, 0x2d, 0xf7, 0x14, 0xf9, 0x56, 0x90, 0x64, 0x06, 0x57, 0x07, 0xbe, 0xef, 0x24, 0x9d, 0xf8,
	0x7a, 0x2f, 0xf2, 0x77, 0xc8, 0xd6, 0xab, 0xe5, 0x2a, 0x3c, 0x1d, 0xe1, 0xc9, 0x05, 0x1c, 0xc5,
	0xb8, 0x02, 0xfc, 0xc1, 0x6d, 0xb5, 0xe3, 0xfa, 0x47, 0x92, 0x7b, 0x40, 0xdc, 0x79, 0x2e, 0x65,
	0x88, 0x3b, 0xf2, 0x0c, 0x58, 0x1b, 0x27, 0x3f, 0x23, 0x6c, 0x2c, 0x84, 0x6e, 0x65, 0x3a, 0xed,
	0xce, 0x37, 0x8d, 0x85, 0xd3, 0xba, 0xb6, 0x91, 0x52, 0xd0, 0xb4, 0x5f, 0xe7, 0x45, 0xfe, 0x9b,
	0xc0, 0x34, 0x9c, 0xfa, 0x0a, 0x99, 0x50, 0xc7, 0xb3, 0x6a, 0x69, 0x32, 0x9f, 0x2c, 0xb2, 0xf2,
	0xa1, 0x18, 0x42, 0x2b, 0xc6, 0xc4, 0x58, 0x3c, 0x49, 0xde, 0xe0, 0x56, 0xd5, 0xa2, 0x1e, 0x48,
	0xe4, 0xc9, 0xc7, 0x88, 0x8c, 0x12, 0x61, 0xff, 0x66, 0x49, 0x09, 0x78, 0x1b, 0xfc, 0xfa, 0xa3,
	0xb3, 0x72, 0x16, 0x81, 0x43, 0x16, 0x6c, 0x1c, 0x3b, 0x59, 0xf9, 0xb6, 0x5c, 0x49, 0x6f, 0x25,
	0x65, 0xbd, 0xd8, 0x5e, 0xfb, 0x4f, 0x7e, 0xf9, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x2b, 0xb9,
	0xd7, 0xf1, 0x01, 0x00, 0x00,
}
