// Code generated by protoc-gen-go.
// source: dmx.proto
// DO NOT EDIT!

/*
Package transport is a generated protocol buffer package.

It is generated from these files:
	dmx.proto

It has these top-level messages:
	DMXCommand
	DMXCommands
*/
package transport

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DMXCommand struct {
	Universe uint32 `protobuf:"varint,1,opt,name=universe" json:"universe,omitempty"`
	Channel  uint32 `protobuf:"varint,2,opt,name=channel" json:"channel,omitempty"`
	Value    uint32 `protobuf:"varint,3,opt,name=value" json:"value,omitempty"`
}

func (m *DMXCommand) Reset()                    { *m = DMXCommand{} }
func (m *DMXCommand) String() string            { return proto.CompactTextString(m) }
func (*DMXCommand) ProtoMessage()               {}
func (*DMXCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DMXCommand) GetUniverse() uint32 {
	if m != nil {
		return m.Universe
	}
	return 0
}

func (m *DMXCommand) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *DMXCommand) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DMXCommands struct {
	Commands []*DMXCommand `protobuf:"bytes,1,rep,name=commands" json:"commands,omitempty"`
}

func (m *DMXCommands) Reset()                    { *m = DMXCommands{} }
func (m *DMXCommands) String() string            { return proto.CompactTextString(m) }
func (*DMXCommands) ProtoMessage()               {}
func (*DMXCommands) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DMXCommands) GetCommands() []*DMXCommand {
	if m != nil {
		return m.Commands
	}
	return nil
}

func init() {
	proto.RegisterType((*DMXCommand)(nil), "transport.DMXCommand")
	proto.RegisterType((*DMXCommands)(nil), "transport.DMXCommands")
}

func init() { proto.RegisterFile("dmx.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0xc9, 0xad, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2c, 0x29, 0x4a, 0xcc, 0x2b, 0x2e, 0xc8, 0x2f, 0x2a,
	0x51, 0x8a, 0xe0, 0xe2, 0x72, 0xf1, 0x8d, 0x70, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x11, 0x92,
	0xe2, 0xe2, 0x28, 0xcd, 0xcb, 0x2c, 0x4b, 0x2d, 0x2a, 0x4e, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0d, 0x82, 0xf3, 0x85, 0x24, 0xb8, 0xd8, 0x93, 0x33, 0x12, 0xf3, 0xf2, 0x52, 0x73, 0x24, 0x98,
	0xc0, 0x52, 0x30, 0xae, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0x33, 0x58,
	0x1c, 0xc2, 0x51, 0x72, 0xe0, 0xe2, 0x46, 0x98, 0x5c, 0x2c, 0x64, 0xc8, 0xc5, 0x91, 0x0c, 0x65,
	0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x89, 0xea, 0xc1, 0x9d, 0xa1, 0x87, 0x50, 0x19, 0x04,
	0x57, 0x96, 0xc4, 0x06, 0x76, 0xad, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xde, 0x5e, 0x86, 0xc2,
	0xba, 0x00, 0x00, 0x00,
}
